---
title: "Final Project"
author: "Paloma Cartwright, Allie Cole, Wylie Hampson, Ben Moscona-Remnitz, Julia Parish"
date: '2022-06-01'
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
output: 
  pdf_document:
    extra_dependencies: ["float"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.pos='!H')
```

# Project Title

This text sentiment analysis was completed as an assignment for the course, Environmental Data Science 231: Text and Sentiment Analysis for Environmental Problems. The data was sourced from  ...

Original assignment instructions can be found [here](https://maro406.github.io/EDS_231-text-sentiment/Group_Project.html)

### Load Libraries

```{r packages}
#install packages as necessary, then load libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(here,
                 igraph,
                 kableExtra,
                 ldatuning,
                 LDAvis,
                 LexisNexisTools,
                 lubridate,
                 pdftools,
                 quanteda,
                 quanteda.textplots,
                 quanteda.textstats,
                 readr,
                 reshape2,
                 sentimentr,
                 tidyr,
                 tidytext,
                 tidyverse,
                 tm,
                 topicmodels,
                 tsne)
```


# test data read in

```{r}
folder <- here("data/")

farm_data <- list.files(pattern = ".DOCX", path = folder, 
                        full.names = TRUE, recursive = TRUE, ignore.case = TRUE)

# lnt_read = read in a LexisNexis file
data <- lnt_read(farm_data) 
```

```{r}
meta_df <- data@meta
articles_df <- data@articles
paragraphs_df <- data@paragraphs
```

```{r}

headline_df<- data_frame(element_id = seq(1:length(meta_df$Headline)), Date = meta_df$Date, 
                  Headline = meta_df$Headline)

paragraphs_df <- data_frame(element_id = paragraphs_df$Art_ID, Text  = paragraphs_df$Paragraph)

ipm_data <- inner_join(headline_df, paragraphs_df, by = "element_id")
```



